FROM mcr.microsoft.com/devcontainers/base:ubuntu
# Install the xz-utils package
RUN apt-get update && apt-get install -y xz-utils
RUN apt-get install python3-pip -y
WORKDIR /app
COPY . /app
EXPOSE 5000
RUN pip install flask
RUN pip install sqlalchemy
CMD python3 ./flaskapp.py